### ISSUE TITLE
get error after parsing

### ISSUE THREAD

**Issue by lpeter218065** [yasp-dota/yasp#1035]
Hi, 

the following is the call stack. 
I just upload a dem file,  then click request parse.

I can see from the parser log, it succeed. Seems the step afterwards generated the error.
Do you meet the error before? can you kindly explain this ? 

Thanks,
Ruiqing 

error: invalid input syntax for integer: "NaN"
   at Connection.parseE (/usr/src/yasp/node_modules/pg/lib/connection.js:539:11)
   at Connection.parseMessage (/usr/src/yasp/node_modules/pg/lib/connection.js:366:17)
   at Socket.<anonymous> (/usr/src/yasp/node_modules/pg/lib/connection.js:105:22)
   at emitOne (events.js:90:13)
   at Socket.emit (events.js:182:7)
   at readableAddChunk (_stream_readable.js:153:18)
   at Socket.Readable.push (_stream_readable.js:111:10)
   at TCP.onread (net.js:529:20)
From previous event:
   at Client._query (/usr/src/yasp/node_modules/knex/lib/dialects/postgres/index.js:150:12)
   at Client.query (/usr/src/yasp/node_modules/knex/lib/client.js:136:24)
   at Runner.<anonymous> (/usr/src/yasp/node_modules/knex/lib/runner.js:115:24)
From previous event:
   at /usr/src/yasp/node_modules/knex/lib/runner.js:43:21
   at tryOnImmediate (timers.js:534:15)
   at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
   at Runner.run (/usr/src/yasp/node_modules/knex/lib/runner.js:29:20)
   at QueryBuilder.Target.then (/usr/src/yasp/node_modules/knex/lib/interface.js:26:43)
   at QueryBuilder.Target.(anonymous function) [as asCallback] (/usr/src/yasp/node_modules/knex/lib/interface.js:77:23)
   at getMatch (/usr/src/yasp/store/queries.js:431:8)
   at Command.callback (/usr/src/yasp/store/buildMatch.js:29:13)
   at normal_reply (/usr/src/yasp/node_modules/redis/index.js:662:21)
   at RedisClient.return_reply (/usr/src/yasp/node_modules/redis/index.js:722:9)
   at JavascriptReplyParser.RedisClient.reply_parser.Parser.returnReply (/usr/src/yasp/node_modules/redis/index.js:146:18)
   at JavascriptReplyParser.run (/usr/src/yasp/node_modules/redis-parser/lib/javascript.js:137:18)
   at JavascriptReplyParser.execute (/usr/src/yasp/node_modules/redis-parser/lib/javascript.js:112:10)
   at Socket.<anonymous> (/usr/src/yasp/node_modules/redis/index.js:223:27)
   at emitOne (events.js:90:13)
   at Socket.emit (events.js:182:7)
   at readableAddChunk (_stream_readable.js:153:18)
   at Socket.Readable.push (_stream_readable.js:111:10)
   at TCP.onread (net.js:529:20)

**Comment by howardchung** [comment]
I've seen this a couple of times.  Do you have the replay file?

**Comment by lpeter218065** [comment]
yes, attached 
[2332828356.zip](https://github.com/yasp-dota/yasp/files/258479/2332828356.zip)

**Comment by howardchung** [comment]
forgot to set a property on the object generated after upload parse.  thanks for finding it.
