### ISSUE TITLE
parseManager occasionally crashes

### ISSUE THREAD

**Issue by howardchung** [yasp-dota/yasp#600]
The error seems to be either kue/redis related: "Job x is invalid".
```
parseManager-2 (err): Error: job "1677583" is invalid
parseManager-2 (err):     at /home/yasp/yasp/node_modules/kue/lib/queue/job.js:173:17
parseManager-2 (err):     at try_callback (/home/yasp/yasp/node_modules/redis/index.js:592:9)
parseManager-2 (err):     at RedisClient.return_reply (/home/yasp/yasp/node_modules/redis/index.js:685:13)
parseManager-2 (err):     at ReplyParser.<anonymous> (/home/yasp/yasp/node_modules/redis/index.js:321:14)
parseManager-2 (err):     at ReplyParser.emit (events.js:107:17)
parseManager-2 (err):     at ReplyParser.send_reply (/home/yasp/yasp/node_modules/redis/lib/parser/javascript.js:300:10)
parseManager-2 (err):     at ReplyParser.execute (/home/yasp/yasp/node_modules/redis/lib/parser/javascript.js:211:22)
parseManager-2 (err):     at RedisClient.on_data (/home/yasp/yasp/node_modules/redis/index.js:547:27)
parseManager-2 (err):     at Socket.<anonymous> (/home/yasp/yasp/node_modules/redis/index.js:102:14)
parseManager-2 (err):     at Socket.emit (events.js:107:17)
```

This would be okay if the currently active jobs were requeued, but they aren't, so they stay stuck in queue.

Worker is in charge of requeuing all active jobs when it restarts, not parseManager.

Fixes:
* Figure out what's wrong with Redis/Kue and handle the exception/fix the issue
* make parseManager requeue its jobs when it crashes
* use one thread for each job (memory expensive)

**Comment by howardchung** [comment]
I haven't seen this in production in a few days, hopefully it fixed itself :P
