### ISSUE TITLE
profiler keeps crashing (profiler.js)

### ISSUE THREAD

**Issue by schadowfox** [yasp-dota/yasp#901]
Issue 1)

```
11:30:21 AM profiler.1 |  players sampled: 11
11:30:21 AM profiler.1 |  2016-02-28T10:30:21.248Z - info: getData: http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=<SNIP>&steamids=76561198228517124%2C76561198227672404%2C76561198203128908%2C…
11:30:23 AM profiler.1 |  /home/yasp/yasp/node_modules/bluebird/js/main/async.js:43
11:30:23 AM profiler.1 |          fn = function () { throw arg; };
11:30:23 AM profiler.1 |                             ^
11:30:23 AM profiler.1 |  error: "U" is not a valid binary digit
11:30:23 AM profiler.1 |      at Connection.parseE (/home/yasp/yasp/node_modules/pg/lib/connection.js:539:11)
11:30:23 AM profiler.1 |      at Connection.parseMessage (/home/yasp/yasp/node_modules/pg/lib/connection.js:366:17)
11:30:23 AM profiler.1 |      at Socket.<anonymous> (/home/yasp/yasp/node_modules/pg/lib/connection.js:105:22)
11:30:23 AM profiler.1 |      at emitOne (events.js:77:13)
11:30:23 AM profiler.1 |      at Socket.emit (events.js:169:7)
11:30:23 AM profiler.1 |      at readableAddChunk (_stream_readable.js:146:16)
11:30:23 AM profiler.1 |      at Socket.Readable.push (_stream_readable.js:110:10)
11:30:23 AM profiler.1 |      at TCP.onread (net.js:523:20)
11:30:23 AM profiler.1 |  From previous event:
11:30:23 AM profiler.1 |      at Client._query (/home/yasp/yasp/node_modules/knex/lib/dialects/postgres/index.js:150:12)
11:30:23 AM profiler.1 |      at Client.query (/home/yasp/yasp/node_modules/knex/lib/client.js:127:24)
11:30:23 AM profiler.1 |      at Runner.<anonymous> (/home/yasp/yasp/node_modules/knex/lib/runner.js:116:24)
11:30:23 AM profiler.1 |  From previous event:
11:30:23 AM profiler.1 |      at /home/yasp/yasp/node_modules/knex/lib/runner.js:44:21
11:30:23 AM profiler.1 |  From previous event:
11:30:23 AM profiler.1 |      at Runner.run (/home/yasp/yasp/node_modules/knex/lib/runner.js:30:20)
11:30:23 AM profiler.1 |      at QueryBuilder.Target.then (/home/yasp/yasp/node_modules/knex/lib/interface.js:27:43)
11:30:23 AM profiler.1 |      at QueryBuilder.Target.(anonymous function) [as asCallback] (/home/yasp/yasp/node_modules/knex/lib/interface.js:78:23)
11:30:23 AM profiler.1 |      at /home/yasp/yasp/queries.js:93:16
11:30:23 AM profiler.1 |      at /home/yasp/yasp/queries.js:79:9
11:30:23 AM profiler.1 |      at /home/yasp/yasp/queries.js:58:13
11:30:23 AM profiler.1 |      at processImmediate [as _immediateCallback] (timers.js:383:17)
11:30:23 AM profiler.1 |  [nodemon] app crashed - waiting for file changes before starting...
```

or

```
11:32:42 AM profiler.1 |  players sampled: 3
11:32:42 AM profiler.1 |  2016-02-28T10:32:42.379Z - info: getData: http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=<SNIP>&steamids=76561198125524761%2C76561198072247745%2C76561198072695004%2C…
11:32:44 AM profiler.1 |  /home/yasp/yasp/node_modules/bluebird/js/main/async.js:43
11:32:44 AM profiler.1 |          fn = function () { throw arg; };
11:32:44 AM profiler.1 |                             ^
11:32:44 AM profiler.1 |  error: "P" is not a valid binary digit
11:32:44 AM profiler.1 |      at Connection.parseE (/home/yasp/yasp/node_modules/pg/lib/connection.js:539:11)
11:32:44 AM profiler.1 |      at Connection.parseMessage (/home/yasp/yasp/node_modules/pg/lib/connection.js:366:17)
11:32:44 AM profiler.1 |      at Socket.<anonymous> (/home/yasp/yasp/node_modules/pg/lib/connection.js:105:22)
11:32:44 AM profiler.1 |      at emitOne (events.js:77:13)
11:32:44 AM profiler.1 |      at Socket.emit (events.js:169:7)
11:32:44 AM profiler.1 |      at readableAddChunk (_stream_readable.js:146:16)
11:32:44 AM profiler.1 |      at Socket.Readable.push (_stream_readable.js:110:10)
11:32:44 AM profiler.1 |      at TCP.onread (net.js:523:20)
11:32:44 AM profiler.1 |  From previous event:
11:32:44 AM profiler.1 |      at Client._query (/home/yasp/yasp/node_modules/knex/lib/dialects/postgres/index.js:150:12)
11:32:44 AM profiler.1 |      at Client.query (/home/yasp/yasp/node_modules/knex/lib/client.js:127:24)
11:32:44 AM profiler.1 |      at Runner.<anonymous> (/home/yasp/yasp/node_modules/knex/lib/runner.js:116:24)
11:32:44 AM profiler.1 |  From previous event:
11:32:44 AM profiler.1 |      at /home/yasp/yasp/node_modules/knex/lib/runner.js:44:21
11:32:44 AM profiler.1 |  From previous event:
11:32:44 AM profiler.1 |      at Runner.run (/home/yasp/yasp/node_modules/knex/lib/runner.js:30:20)
11:32:44 AM profiler.1 |      at QueryBuilder.Target.then (/home/yasp/yasp/node_modules/knex/lib/interface.js:27:43)
11:32:44 AM profiler.1 |      at QueryBuilder.Target.(anonymous function) [as asCallback] (/home/yasp/yasp/node_modules/knex/lib/interface.js:78:23)
11:32:44 AM profiler.1 |      at /home/yasp/yasp/queries.js:93:16
11:32:44 AM profiler.1 |      at /home/yasp/yasp/queries.js:79:9
11:32:44 AM profiler.1 |      at /home/yasp/yasp/queries.js:58:13
11:32:44 AM profiler.1 |      at processImmediate [as _immediateCallback] (timers.js:383:17)
11:32:44 AM profiler.1 |  [nodemon] app crashed - waiting for file changes before starting...
```

Issue 2)
profiler also keeps requesting even if steamids is empty

```
11:35:01 AM profiler.1 |  players sampled: 0
11:35:01 AM profiler.1 |  2016-02-28T10:35:01.266Z - info: getData: http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=<SNIP>&steamids=
11:35:04 AM profiler.1 |  players sampled: 0
11:35:04 AM profiler.1 |  2016-02-28T10:35:04.507Z - info: getData: http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=<SNIP>&steamids=

```

**Comment by howardchung** [comment]
I recently changed the sampling algorithm to be more efficient and not require upsert of all the players in a match.

I'm not sure exactly what's wrong here.  It looks like the profiler is successfully sampling players and sending the request, but crashes on insert?  I didn't change the insertion code so I'm not sure exactly what's wrong.  You may want to put in traces/attach debugger so you can step through and see exactly what's going on.

For the empty case you could submit a patch to skip the request if the returned array has length zero.

**Comment by schadowfox** [comment]
Already submitted the empty case patch :)

**Comment by schadowfox** [comment]
Found the problem - for some reason I had loccountrycode not as varchar, weird, anyway issue 1 solved as well~ yay!
